language: node_js
node_js:
- '6'
env:
  global:
    secure: NJTv9o+edt2UihTCK/yHk/EOcfTo/nD737mzWhMoNixSkLP5NiN/iqMEpXCQL1gLhJ8+697PiXw6x1eFk+U1ABJEq3WGdd8VICaGkFGRAvkyIXaVngR4hN4mcup+odepQ5vopXCXL0hEA29kMqllD6rqh/MAVsIGhfXbMU/UnuBj3sHFMyKOmNIMQClDQ7NhpX+eOde0dkQAtwTvTp/op/PMQeOFH0d5XMZB2GqCqAxSisIhHN2a00jzKvz5a1/nHJ/QT3mtQlw29s25VzOTrEZeblgNk8auHwfNHuZcDhQhS9Q4Ivbh9Ql+YweYVz3qXjlHDpz5f4nq7ZJrDVM7aMttF9b7xtj7FgXYSLzhIs7S9dE4aUb1m3+U/WCmGqFA7h/Te4xxXBr5hTGNHuUxuU4w1itBYnnwUHclfUVIWIec2+aM6zL2VyiidxIhsePQE6TppgJ8OG2jMaaUAJ7VwQ7XAxAe4NwWLx9FxKjb8VvyzhMGwqYFJGREvv0pLK87ApnHeIVA5dswDerkJFIhP/UtxoMWcsgrGxwv0WgJBv1ZVqlHCytMeVMySUHgIYvRQc5NltG1vTOCgLG0pjxXaGbtqYE5NZPoBeRiVFBmVF0UZblX8WqEF0silH6/KVHeaggt61+qHzNgtj+0iGb4w1dqKsOg6ygySrXFSC/KvpE=
